name: Intouch Health
favicon: null
layout_spectrum: 0.9945609224960208
typography_spectrum: 0.9910917377565056
title: Intouch Exercise Physiology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6058826127555221
  lightness: 0.30236738780513406
  saturation: 0.5895744732115418
  rhythmicContrast: 0.013910353416576982
purpose: []
